POST  http://localhost:5000/api/auth/register

Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}


###

http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E1MDFlNmUxMzYyZWVlZWEyZGE0MzciLCJpYXQiOjE2NzE3NjQyNDZ9.1M783PnGJ3B5JY-SIA2mFFIGxlrlt7Z7_KTp-xCwAjs

