export const apiUrl =
  process.env.NODE_ENV !== "production"
    ? "http://localhost:5000/api"
    : "somedeployURL";
export const LOCAL_STORAGE_TOKEN_NAME = "connycar";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const VEHICLE_FETCH_REQUEST = "VEHICLE_FETCH_REQUEST";
export const VEHICLE_FETCH_SUCCESS = "VEHICLE_FETCH_SUCCESS";
export const VEHICLE_FETCH_FAIL = "VEHICLE_FETCH_FAIL";

export const VEHICLE_CREATE_REQUEST = "VEHICLE_CREATE_REQUEST";
export const VEHICLE_CREATE_SUCCESS = "VEHICLE_CREATE_SUCCESS";
export const VEHICLE_CREATE_FAIL = "VEHICLE_CREATE_FAIL";

export const VEHICLE_UPDATE_REQUEST = "VEHICLE_UPDATE_REQUEST";
export const VEHICLE_UPDATE_SUCCESS = "VEHICLE_UPDATE_SUCCESS";
export const VEHICLE_UPDATE_FAIL = "VEHICLE_UPDATE_FAIL";

export const VEHICLE_DELETE_REQUEST = "VEHICLE_DELETE_REQUEST";
export const VEHICLE_DELETE_SUCCESS = "VEHICLE_DELETE_SUCCESS";
export const VEHICLE_DELETE_FAIL = "VEHICLE_DELETE_FAIL";
