export const apiUrl =
  process.env.NODE_ENV !== "production"
    ? "http://localhost:5000/api"
    : "somedeployURL";
export const LOCAL_STORAGE_TOKEN_NAME = "connycar";
export const SET_AUTH = "SET_AUTH";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const LOGIN_BY_GOOGLE_REQUEST = "LOGIN_BY_GOOGLE_REQUEST";
export const VEHICLE_FETCH_REQUEST = "VEHICLE_FETCH_REQUEST";
export const VEHICLE_FETCH_SUCCESS = "VEHICLE_FETCH_SUCCESS";
export const VEHICLE_FETCH_FAIL = "VEHICLE_FETCH_FAIL";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const VEHICLE_CREATE_REQUEST = "VEHICLE_CREATE_REQUEST";
export const VEHICLE_CREATE_SUCCESS = "VEHICLE_CREATE_SUCCESS";
export const VEHICLE_CREATE_FAIL = "VEHICLE_CREATE_FAIL";

export const VEHICLE_UPDATE_REQUEST = "VEHICLE_UPDATE_REQUEST";
export const VEHICLE_UPDATE_SUCCESS = "VEHICLE_UPDATE_SUCCESS";
export const VEHICLE_UPDATE_FAIL = "VEHICLE_UPDATE_FAIL";

export const VEHICLE_DELETE_REQUEST = "VEHICLE_DELETE_REQUEST";
export const VEHICLE_DELETE_SUCCESS = "VEHICLE_DELETE_SUCCESS";
export const VEHICLE_DELETE_FAIL = "VEHICLE_DELETE_FAIL";

export const HISTORY_FETCH_SUCCESS = "HISTORY_FETCH_SUCCESS";
export const HISTORY_FETCH_FAIL = "HISTORY_FETCH_FAIL";

export const BOOKING_CREATE_FAIL = "BOOKING_CREATE_FAIL";
export const BOOKING_CREATE_SUCCESS = "BOOKING_CREATE_SUCCESS";
export const BOOKING_CREATE_REQUEST = "BOOKING_CREATE_REQUEST";

export const BOOKING_UPDATE_FAIL = "BOOKING_UPDATE_FAIL";
export const BOOKING_UPDATE_SUCCESS = "BOOKING_UPDATE_SUCCESS";
export const BOOKING_UPDATE_REQUEST = "BOOKING_UPDATE_REQUEST";

export const BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL";
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const BOOKING_DELETE_REQUEST = "BOOKING_DELETE_REQUEST";

export const BOOKING_FETCH_FAIL = "BOOKING_FETCH_FAIL";
export const BOOKING_FETCH_SUCCESS = "BOOKING_FETCH_SUCCESS";
export const BOOKING_FETCH_REQUEST = "BOOKING_FETCH_REQUEST";

export const DISCOUNT_CREATE_FAIL = "DISCOUNT_CREATE_FAIL";
export const DISCOUNT_CREATE_SUCCESS = "DISCOUNT_CREATE_SUCCESS";
export const DISCOUNT_CREATE_REQUEST = "DISCOUNT_CREATE_REQUEST";

export const DISCOUNT_UPDATE_FAIL = "DISCOUNT_UPDATE_FAIL";
export const DISCOUNT_UPDATE_SUCCESS = "DISCOUNT_UPDATE_SUCCESS";
export const DISCOUNT_UPDATE_REQUEST = "DISCOUNT_UPDATE_REQUEST";

export const DISCOUNT_DELETE_FAIL = "DISCOUNT_DELETE_FAIL";
export const DISCOUNT_DELETE_SUCCESS = "DISCOUNT_DELETE_SUCCESS";
export const DISCOUNT_DELETE_REQUEST = "DISCOUNT_DELETE_REQUEST";

export const DISCOUNT_FETCH_FAIL = "DISCOUNT_FETCH_FAIL";
export const DISCOUNT_FETCH_SUCCESS = "DISCOUNT_FETCH_SUCCESS";
export const DISCOUNT_FETCH_REQUEST = "DISCOUNT_FETCH_REQUEST";
